name: swaa-misfit-sustainability
channels:
  - conda-forge
dependencies:
  - python=3.13
  - pandas=2.2.3
  - numpy=2.3.5
  - scikit-learn=1.8.0
  - statsmodels=0.14.6
  - matplotlib=3.10.8
  - pip
  - pip:
      - python-docx==1.2.0
